# Variables
substitutions:
  _APP_NAME: cthdb-api

steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:online-ventures/$_APP_NAME.git

- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

- name: gcr.io/cloud-builders/docker
  dir: $_APP_NAME
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA',
    '-f', 'config/docker/web/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '.']
  timeout: 600s

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

# Get access key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=config/cloudbuild/token.enc
  - --plaintext-file=/root/.profile
  - --location=global
  - --keyring=cloud-build
  - --key=digital-ocean-access-key
  volumes:
  - name: 'home'
    path: /root

# Set up kubectl
- name: 'gcr.io/cloud-builders/curl'
  args: [
    '-X', 'GET',
    'http://api.digitalocean.com/v2/clusters/$CLUSTER_ID/kubeconfig',
    '-H', 'Authorization: Bearer $TOKEN',
    '>', '/root/.kube/config']
  volumes:
  - name: 'home'
    path: /root
  - name: 'kube'
    path: /root/.kube

# Update cluster pods
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deploy/$_APP_NAME'
    - 'app=gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
    - '--namespace=default'

# Save this build as well according to commit sha
images:
- 'gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
